language: haskell

ghc:
  - "8.2"
  - "8.0"
  - "7.10"
  - "7.8"
  - "7.6"
  - "7.4"

install:
  git clone https://github.com/eth-r/base32-bytestring ../b32
  cabal install ../b32
  cabal install --only-dependencies --enable-tests

script:
  cabal configure && cabal build && cabal test
